// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nera.Web.Data;

namespace Nera.Web.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200803231053_CompleteBD")]
    partial class CompleteBD
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Nera.Web.Data.Entities.RegistroRescate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comentarios");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<bool>("Estado");

                    b.Property<int>("Odometro");

                    b.Property<int?>("RescateId");

                    b.Property<int?>("VehiculoId");

                    b.HasKey("Id");

                    b.HasIndex("RescateId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("RegistroRescates");
                });

            modelBuilder.Entity("Nera.Web.Data.Entities.Rescate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Comentarios");

                    b.Property<DateTime>("Fecha");

                    b.Property<string>("ImageUrl");

                    b.Property<int?>("RescatistaID");

                    b.Property<int?>("TipoRescateId");

                    b.HasKey("Id");

                    b.HasIndex("RescatistaID");

                    b.HasIndex("TipoRescateId");

                    b.ToTable("Rescates");
                });

            modelBuilder.Entity("Nera.Web.Data.Entities.Rescatista", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Celular")
                        .HasMaxLength(15);

                    b.Property<string>("Direccion")
                        .HasMaxLength(100);

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Rut")
                        .IsRequired()
                        .HasMaxLength(11);

                    b.Property<string>("Telefono")
                        .HasMaxLength(15);

                    b.HasKey("ID");

                    b.ToTable("Rescatistas");
                });

            modelBuilder.Entity("Nera.Web.Data.Entities.TipoRescate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("TipoRescates");
                });

            modelBuilder.Entity("Nera.Web.Data.Entities.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("Nera.Web.Data.Entities.RegistroRescate", b =>
                {
                    b.HasOne("Nera.Web.Data.Entities.Rescate", "Rescate")
                        .WithMany("RegistroRescates")
                        .HasForeignKey("RescateId");

                    b.HasOne("Nera.Web.Data.Entities.Vehiculo", "Vehiculo")
                        .WithMany("RegistroRescates")
                        .HasForeignKey("VehiculoId");
                });

            modelBuilder.Entity("Nera.Web.Data.Entities.Rescate", b =>
                {
                    b.HasOne("Nera.Web.Data.Entities.Rescatista", "Rescatista")
                        .WithMany("Rescates")
                        .HasForeignKey("RescatistaID");

                    b.HasOne("Nera.Web.Data.Entities.TipoRescate", "TipoRescate")
                        .WithMany("Rescates")
                        .HasForeignKey("TipoRescateId");
                });
#pragma warning restore 612, 618
        }
    }
}
